config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs

  resources :wishes do
    member do
      patch :update_status
    end
  end

  root to: "home#homepage"
  get 'homepage', to: 'home#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wish.rb
class Wish < ApplicationRecord
  validates :status, presence: true
  STATUSES = [:granted, :waiting]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end
  
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "Blog Created"
    else 
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "Blog Updated"
    else
      render :edit
    end
  end

  def destroy
    if @blog.destroy
      redirect_to blogs_path, notice: "Blog has been deleted"
    end
  end

  private 
  
  def blog_params
    params.require(:blog).permit(:title, :author, :body)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def homepage
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:update_status, :show, :edit, :update, :destroy]

  def index
    @wishes = Wish.all
  end

  def update_status
    @wish.update(status: params[:status])
    redirect_to @wish, notice:"Wish status is changed to #{@wish.status}"
  end

  def new
    @wish = Wish.new
  end

  def create
    @wish = Wish.new(wish_params)
    if @wish.save
      redirect_to wishes_path, notice: "Wish added!"
    else
      render :new
    end
  end

  def show
  end

  def update
    if @wish.update(wish_params)
      redirect_to wishes_path, notice: "Wish updated!"
    else
      render :edit
    end
  end

  def destroy
    if @wish.destroy
      redirect_to wishes_path, notice: "Wish deleted!"
    end
  end

  private
    
  def wish_params
    params.require(:wish).permit(:name, :expected_date, :created_at)
  end

  def set_wish
    @wish = Wish.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <div class="field">
  Title: <%= f.text_field :title, placeholder: "Legend of the blue sea", required: true %>
  </div><br>
  <div class="field">
  Author: <%= f.text_field :author, placeholder: "Cathy Molina-Garcia" %>
  </div><br>
  <div class="field">
  Body: <%= f.text_area :body, placeholder: "Write your blog here", required: true %>
  </div><br>

  <div class="actions">
  <%= f.submit class:"btn btn-success" %>
  </div><br>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit your blog</h1>

<%= render "form", blog: @blog %>
<%= link_to "Cancel", blogs_path, class:"btn btn-secondary" %>

app/views/blogs/index.html.erb
<table class="table table-sm table-hover table-bordered mt-3">
  <thead class="table table-light table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.author %></td>
        <td><%= link_to "Read more", blog_path(blog), class:"btn btn-sm btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create a blog", new_blog_path, class:"btn btn-success" %><br><br>
<%= link_to "Back", homepage_path, class:"btn btn-secondary" %>

app/views/blogs/new.html.erb
<h1>Write your blog!</h1>

<%= render "form" %>
<%= link_to "Back", blogs_path, class:"btn btn-secondary" %>

app/views/blogs/show.html.erb
<h3><strong><%= @blog.title %></strong></h3>
<strong>By: <%= @blog.author %></strong><br><br>
<p><%= @blog.body %></p>

<%= link_to "Back", blogs_path, class:"btn btn-secondary" %>
<%= link_to "Edit", edit_blog_path(@blog), class:"btn btn-success" %>
<%= link_to "Delete", blog_path(@blog), class:"btn btn-danger", method: :delete, data: {confirm:"Are you sure?"} %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "DonCreations", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wish" %>
        </li>
        <li class="nav-item">
          <%= link_to "About" %>
        </li>
        <li class="nav-item">
          <%= link_to "Settings" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/homepage.html.erb
<h1>Homepage</h1><strong>Go to:</strong>

<%= link_to "Articles", blogs_path, class:"btn btn-info"%>
<%= link_to "Wishes", wishes_path, class:"btn btn-success"%>

app/views/layouts/_alerts.html.erb
<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% elsif alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_session_manager.html.erb
<% if user_signed_in? %>
  Me:<%= current_user.email %>

  <div class="float-end">
    <%= link_to "Log Out",
      destroy_user_session_path,
      method: :delete,
      class: "btn btn-sm btn-dark"
    %>
    <%= link_to "Security and Login",
      edit_user_registration_path,
      class: "btn btn-sm btn-dark"
    %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="container">
    <title>DonCreations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </div>
  </head>

  <body>
    <header>
      <%= render "layouts/session_manager" %>
      <%= render "layouts/alerts" %>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/wishes/_form.html.erb
<%= form_for @wish do |w| %>
  <div class="field">
  <%= w.text_field :name, placeholder: "Enter your wish here", required: true, autofocus: true %> 
  </div>
  <div class="field">
  Pick your expected date: <br><%= w.date_field :expected_date, required: true %>
  </div><br>

  <div class="actions">
  <%= w.submit class:"btn btn-warning" %>
  </div><br>
<% end %>

app/views/wishes/edit.html.erb
<h1>Edit your wish</h1>

<%= render "form", wish: @wish %>
<%= link_to "Cancel", wishes_path, class:"btn btn-secondary" %>

app/views/wishes/index.html.erb
<h1>Wish list</h1>

<%= link_to "Add a wish", new_wish_path, class:"btn btn-warning" %>

<table class="table table-sm table-hover table-bordered border-dark mt-3">
  <thead class="table table-light table-bordered border-dark">
    <tr>
      <th>Wish</th>
      <th>Created at</th>
      <th>Expecting at</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <body>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= wish.name %></td>
        <td><%= wish.created_at.strftime("%a %b %d, %Y") %></td>
        <td><%= wish.expected_date.strftime("%a %b %d, %Y") %></td>
        <td><%= link_to "Show", wish_path(wish), class:"btn btn-sm btn-primary" %></td>
        <td><%= link_to "Edit", edit_wish_path(wish), class:"btn btn-sm btn-success"%></td>
        <td><%= link_to "Remove", wish_path(wish), class:"btn btn-sm btn-danger", method: :delete, data: {confirm: "Pindutin ang 'ok' kung sure ka na"} %></td>
      </tr>
    <% end %>
  </body>
</table>

<%= link_to "Home", homepage_path, class:"btn btn-secondary" %>

app/views/wishes/new.html.erb
<h1>Add wish</h1>

<%= render "form" %>
<%= link_to "Cancel", wishes_path, class:"btn btn-secondary" %>

app/views/wishes/show.html.erb
<h1>Wish</h1>

<p class="lead">Wish: <strong><%= @wish.name %></strong></p>
<p class="lead">Expecting at: </strong><%= @wish.expected_date %></strong></p>
<p class="lead">Status: <strong><%= @wish.status %>
  <% Wish::STATUSES.each do |status| %>
    <%= link_to_unless @wish.status.eql?(status.to_s), status, update_status_wish_path(@wish, status: status), method: :patch %>
  <% end %>
</strong></p> 

<%= link_to "Back", wishes_path, class:"btn btn-secondary" %>